# Host-specific Hyprland config for framework-13

exec-once = kdeconnect-indicator
exec-once = hyprsunset
exec-once = systemctl --user start easyeffects.service
exec-once = systemctl --user start vicinae.service
exec-once = aw-watcher-window-hyprland

bind = $mainMod, Space, exec, $menu
bind = $mainMod SHIFT, Space, exec, wofi --show run
bind = $mainMod, TAB, exec, vicinae vicinae://launch/wm/switch-windows
