g# ------------------------------------------------------------------------
# Aliases
# ------------------------------------------------------------------------
Alt   = AltLeft
AltGr = AltRight
Win   = Meta
Left   = ArrowLeft
Right   = ArrowRight

# ------------------------------------------------------------------------
# Pass Modifier Keys through
# TODO: MIGRATE TO THIS & REMOVE !Alt ... below:
# @forward-modifiers Shift Control AltLeft
# ------------------------------------------------------------------------
Control >> Control
Shift >> Shift
Alt >> Alt


# ------------------------------------------------------------------------
# Global mappings
# ------------------------------------------------------------------------
PageUp >> AudioVolumeUp
PageDown >> AudioVolumeDown
Home >> MediaPlayPause
Insert >> Meta{A}
End >> F11
MediaTrackPrevious >> NumLock
MediaTrackNext >> NumLock

[system = "Linux"]

# W/ Workaround
(Control Alt){P} >> !Alt (Control Shift){F6}


# ------------------------------------------------------------------------
# Application-specific mappings
# ------------------------------------------------------------------------

# Zen
# ---------
# [system = "Linux", title = "app.zen_browser.zen"]
# [system = "Linux", class = "zen"]
# [system = "Windows", path = "zen.exe"]
[title = /Zen Browser/i]

# W/ Workarounds
# (Control Shift){P} >> !Control Alt{D}
(Control Shift){E} >> (Control Shift){B}

# W/ Workarounds
# Control{D} >> !Control Alt{P}
# (Alt){P} >> (Control Alt){J}

!Shift Control{P} >> Control{T}

# Chrome
# ---------
[system = "Linux", class = "google-chrome"]
[system = "Windows", path = "chrome.exe"]

# W/ Workarounds
# (Control Shift){P} >> !Shift Control{L}
(Control Shift){P} >> (Control Shift){A}

# Control{P} >> Control{T}

# Spotify
# ---------
[system = "Linux", class = "spotify"]
[system = "Windows", path = "spotify.exe"]

(Control Shift){P} >> !Control K


# Obsidian
# ---------
# [system = "Linux", class = "obsidian"]

# For Future Focus Mode
# (Control K) Z >> (Control Alt Shift){Z}
