[general]
destination = "/home/e/.config/hypr/monitors.conf"

[power_events]

[power_events.dbus_query_object]
path = "/org/freedesktop/UPower/devices/line_power_ACAD"

[[power_events.dbus_signal_match_rules]]
object_path = "/org/freedesktop/UPower/devices/line_power_ACAD"


# Home Office
# -> Dell 24" + Xiaomi 34"

[profiles.home_office]
config_file = "/home/e/.config/hyprdynamicmonitors/hyprconfigs/home_office.go.tmpl"
config_file_type = "template"

[profiles.home_office.conditions]

[[profiles.home_office.conditions.required_monitors]]
description = "BOE 0x0BCA"
monitor_tag = "laptop"

[[profiles.home_office.conditions.required_monitors]]
description = "Xiaomi Corporation Mi Monitor"
monitor_tag = "xiaomi-34"

[[profiles.home_office.conditions.required_monitors]]
description = "Dell Inc. DELL U2415 7MT017CK0JAU"
monitor_tag = "dell-24"


# Undocked

[profiles.undocked]
config_file = "/home/e/.config/hyprdynamicmonitors/hyprconfigs/undocked.go.tmpl"
config_file_type = "template"

[profiles.undocked.conditions]

[[profiles.undocked.conditions.required_monitors]]
description = "BOE 0x0BCA"
monitor_tag = "laptop"

[profiles.home-ultrawide]
config_file = "/home/e/.config/hyprdynamicmonitors/hyprconfigs/home-ultrawide.go.tmpl"
config_file_type = "template"


# Home Ultrawide (Single Monitor)
# -> Xiaomi 34"

[profiles.home-ultrawide.conditions]

[[profiles.home-ultrawide.conditions.required_monitors]]
description = "BOE 0x0BCA"
monitor_tag = "laptop"

[[profiles.home-ultrawide.conditions.required_monitors]]
description = "Xiaomi Corporation Mi Monitor"
monitor_tag = "xiaomi-34"


# Home Ultrawide (Dual Monitor)
# -> Xiaomi 34" + Laptop

# [profiles.home-ultrawide-vertical-stack]
# config_file = "/home/e/.config/hyprdynamicmonitors/hyprconfigs/home-ultrawide-vertical-stack.go.tmpl"
# config_file_type = "template"

# [profiles.home-ultrawide-vertical-stack.conditions]

# [[profiles.home-ultrawide-vertical-stack.conditions.required_monitors]]
# description = "BOE 0x0BCA"
# monitor_tag = "laptop"

# [[profiles.home-ultrawide-vertical-stack.conditions.required_monitors]]
# description = "Xiaomi Corporation Mi Monitor"
# monitor_tag = "xiaomi-34"


# Home TV
# -> Philips Home TV

[profiles.TV]
config_file = "/home/e/.config/hyprdynamicmonitors/hyprconfigs/TV.go.tmpl"
config_file_type = "template"
[profiles.TV.conditions]

[[profiles.TV.conditions.required_monitors]]
description = "BOE 0x0BCA"
monitor_tag = "monitor0"

[[profiles.TV.conditions.required_monitors]]
description = "Philips Consumer Electronics Company Philips UHDTV 0x01010101"
monitor_tag = "monitor1"
