general {
	# avoid starting multiple hyprlock instances.
	lock_cmd = pidof hyprlock || hyprlock
	# lock before suspend.
	before_sleep_cmd = loginctl lock-session
	# to avoid having to press a key twice to turn on the display.
	after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
	# 2.5 min.
	timeout = 150
	# set monitor backlight to minimum, avoid 0 on OLED monitor.
	on-timeout = brillo -O && brillo -e -u 150000 -S 10
	# monitor backlight restore.
	on-resume = brillo -e -u 150000 -I
}

# turn off keyboard backlight, comment out this section if you dont have a keyboard backlight.
listener {
	# 2.5 min.
	timeout = 150
	# turn off keyboard backlight.
	on-timeout = brillo -k -S 0
	# turn on keyboard backlight.
	on-resume = brillo -k -I
}

listener {
	# 10 min
	timeout = 600
	
	# lock screen when timeout has passed
	on-timeout = loginctl lock-session
}

listener {
	# 11.5 min
	timeout = 700

	# screen off when timeout has passed
	on-timeout = hyprctl dispatch dpms off

	# screen on when activity is detected after timeout has fired.
	on-resume = hyprctl dispatch dpms on
}

listener {
	# 30 min
	timeout = 1800

	# suspend pc
	on-timeout = systemctl suspend
}